# Generated by Django 5.0.1 on 2024-02-03 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='team_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
